# Site settings
title: HPX - High Performance ParalleX
description: > # this means to ignore newlines until "baseurl:"
  HPX performance analysis reports
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  parsa

# Build settings
markdown: kramdown
